version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/store
      - JWT_SECRET=tearinmyheart
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: